import StyledComponentsRegistry from '@components/layout/StyledComponentsRegistry'
import '../theme/globalImports.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

interface Props {
	children: React.ReactNode
}

const Layout = ({ children }: Props) => {
	return (
		<html lang="en">
			<body>
				<StyledComponentsRegistry>
					{children}
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}

export default Layout